import {days,byDate,START,EXAM,DAY,todayStamp,tasksFor,phaseProgress,duration,courseSeconds} from './plan.mjs?v=20261009d';
import {PlannerStore,emptyDocument,validateDocument} from './planner-store.mjs?v=20261009d';
const $=id=>document.getElementById(id),subjects=['数学','英语','自控','政治','其他'],weekdays=['日','一','二','三','四','五','六'];
const phaseName={foundation:'基础阶段',practice:'真题阶段',open:'自主安排'};
let doc=emptyDocument(),today=todayStamp(),syncState={},removeID=null,toastTimer,activeDay=null;
let storage;try{storage=localStorage}catch{storage={getItem:()=>null,setItem:()=>{throw new Error('Storage unavailable')},removeItem:()=>{}}}
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function button(text,cls,action){const n=node('button','btn '+cls,text);n.type='button';n.addEventListener('click',action);return n}
function link(text,url,cls=''){const a=node('a',cls,text);a.href=url;return a}
const homeURL=()=>location.pathname+'?v=20261009d';
const dayURL=date=>location.pathname+'?v=20261009d&day='+date;
function message(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3300)}
function doneCount(tasks){const checked=new Set(doc.checked);return tasks.filter(t=>checked.has(t.id)).length}
function ring(value,total,accent,label){const wrap=node('div','ring-wrap');wrap.style.setProperty('--accent',accent);const pct=total?Math.round(value/total*100):0;wrap.setAttribute('role','img');wrap.setAttribute('aria-label',`${label}：${value}/${total}，${pct}%`);wrap.innerHTML='<svg viewBox="0 0 80 80" aria-hidden="true"><circle class="ring-bg" cx="40" cy="40" r="34"/><circle class="ring-value" cx="40" cy="40" r="34" pathLength="100"/></svg>';wrap.querySelector('.ring-value').setAttribute('stroke-dasharray',`${pct} 100`);wrap.append(node('strong','',pct+'%'));return wrap}
function headline(title,note,eyebrow,day=false){const section=node('section','hero'+(day?' day-hero':'')),left=node('div');left.append(node('p','eyebrow',eyebrow),node('h1','',title),node('p','subtitle',note));section.append(left);return section}
function syncbar(){const section=node('section','syncbar');section.setAttribute('aria-label','自动保存');const info=node('div','sync-info'),dot=node('span','sync-light');dot.id='sync-light';const status=node('span');status.id='sync-status';status.setAttribute('role','status');info.append(dot,node('strong','','自动保存'),status);const actions=node('div','actions'),retry=button('立即同步','quiet',()=>store.sync(true));retry.id='retry-sync';actions.append(retry);section.append(info,actions);return section}
function renderStatus(){
 const s=syncState,status=$('sync-status');if(status){let text=s.error||(s.running?'正在同步任务与进度…':s.pending?s.connected?'已保存到本机 · 等待自动同步':'已保存到本机 · 此浏览器尚未连接仓库':s.connected&&s.savedAt?'仓库已同步 · '+new Date(s.savedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):s.connected?'已连接 · 正在准备同步':'本机自动保存 · 此浏览器尚未连接仓库');if(s.storageFailed)text='浏览器无法保存到本机，请保持页面打开并等待仓库同步。';status.textContent=text;status.classList.toggle('storage-warning',!!s.storageFailed);$('sync-light').dataset.status=s.error||s.storageFailed?'error':s.running||s.pending?'busy':s.connected?'ok':'off';$('retry-sync').hidden=!s.connected;$('retry-sync').disabled=!!s.running}
 $('copy-sync').hidden=!s.connected;$('disconnect-sync').hidden=!s.connected;
}
function chart(phase){const p=phaseProgress(phase,doc),isBase=phase==='foundation',section=node('section','chart');section.setAttribute('aria-label',isBase?'基础阶段完成情况':'真题阶段完成情况');const heading=node('div','card-heading');heading.append(node('h2','',isBase?'02 / 基础阶段完成':'03 / 真题阶段完成'),node('span','tag',isBase?'10.09 — 10.18':'10.19 — 11.07'));const body=node('div','chart-body'),stats=node('div'),number=node('div','big-stat');number.append(node('span','',p.done),node('small','',`/ ${p.total} 项`));stats.append(number,node('p','',isBase?'880 · 每日200词 · 自控课程':'2007—2026 · 四科真题 + 单词'));body.append(stats,ring(p.done,p.total,isBase?'var(--lime)':'var(--purple)',isBase?'基础任务完成度':'真题任务完成度'));const foot=node('div','chart-foot');foot.append(node('span','',`${p.daysDone} / ${p.days} 天全部完成`),node('span','','含自建任务'));section.append(heading,body,foot);return section}
function timeChart(){const elapsed=Math.max(0,Math.min(71,Math.floor((today-START)/DAY))),card=node('section','chart');card.setAttribute('aria-label','71天时间进度');const heading=node('div','card-heading');heading.append(node('h2','','01 / 时间进度'),node('span','tag','10.09 — 12.18'));const body=node('div','chart-body'),stats=node('div'),num=node('div','big-stat');num.append(node('span','',elapsed),node('small','','/ 71 天已过去'));const ticks=node('div','ticks');ticks.setAttribute('aria-hidden','true');for(let i=0;i<71;i++)ticks.append(node('i',i<elapsed?'elapsed':i===elapsed&&today<EXAM&&today>=START?'current':''));stats.append(num,ticks);body.append(stats,ring(elapsed,71,'var(--teal)','时间进度'));const foot=node('div','chart-foot');foot.append(node('span','',today<START?'计划尚未开始':today>=EXAM?'已到初试日':`今天是第 ${elapsed+1} 天`),node('span','',`还剩 ${71-elapsed} 天 · 含今天`));card.append(heading,body,foot);return card}
function vocabularyCycles(){const section=node('section','vocab-cycles');section.setAttribute('aria-label','核心单词学习周期');const heading=node('div','vocab-heading');heading.append(node('strong','','核心词 · 每 10 天一周期'),node('span','','200 词 / 天 · 2000 词 / 周期'));section.append(heading);const track=node('div','cycle-track');for(let i=0;i<8;i++){const rows=days.slice(i*10,i*10+10),done=rows.filter(d=>doc.checked.includes(d.date+':words')).length,a=link('',dayURL(rows[0].date),'cycle-chip'+(done===10?' complete':''));a.append(node('strong','',`第 ${i+1} 周期`),node('span','',`${done} / 10 天`),node('small','',rows.length===10?rows[0].short+'—'+rows.at(-1).short:'12.18 · 考前安排 1 天'));const progress=node('i');progress.style.width=done/10*100+'%';a.append(progress);track.append(a)}section.append(track);return section}
function logTools(){const details=node('details','log-tools');details.append(node('summary','','日志与备份'));const actions=node('div','actions');actions.append(button('下载全部任务与进度','quiet',()=>{const blob=new Blob([JSON.stringify(doc,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=link('','');a.href=url;a.download='kaoyan-tasks-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}));const history=link('查看仓库历史','https://github.com/tumytime/tumytime.github.io/commits/main/kaoyan/logs/planner-v3.json','btn quiet');history.target='_blank';history.rel='noopener noreferrer';actions.append(history);details.append(actions);if(doc.legacyChecked.length)details.append(node('p','',`旧计划的 ${doc.legacyChecked.length} 项打卡已归档保留；新任务按本次计划重新统计。`));return details}
function renderHome(root){
 const hero=headline('把每一天，落实到位。','10 天打基础，20 年真题逐套落实。今天的任务、每一项进度，都在这里。','目标 · 中国科学院深圳先进技术研究院'),count=node('div','count');count.append(node('strong','',Math.max(0,Math.ceil((EXAM-Math.max(today,START))/DAY))),node('span','','天'),node('small','','距初试 · 含今天'));hero.append(count);const charts=node('div','charts');charts.append(timeChart(),chart('foundation'),chart('practice'));root.append(hero,charts,vocabularyCycles(),syncbar());
 const t=days.find(d=>d.stamp===today)||days[0],tasks=tasksFor(t,doc),todayPanel=node('section','today'),copy=node('div');copy.append(node('h2','',`${t.stamp===today?'今天':'计划首日'} · ${t.short} · ${phaseName[t.phase]}`));let summary=t.phase==='foundation'?[t.calculus?`高数：${t.calculus.title}`:null,`线代：${t.algebra.title}`,t.course?`自控：${t.course[0]}`:null,'200 个单词'].filter(Boolean).join(' / '):t.phase==='practice'?`${t.year} 年政治、英语、数学、自控各 1 套 / 200 个单词`:'200 个单词，其他任务由你安排';copy.append(node('p','',summary+` · 已完成 ${doneCount(tasks)} / ${tasks.length} 项`));todayPanel.append(copy,link('进入当天任务 →',dayURL(t.date),'btn primary'));root.append(todayPanel);
 const board=node('section','board'),heading=node('div','board-heading');heading.append(node('h2','','71 天，连续推进'),node('span','','点击任意日期，进入当天任务页'));board.append(heading);const legend=node('div','legend');for(const [cls,label,dates]of [['base-swatch','基础阶段 · 10 天','10.09—10.18'],['paper-swatch','真题阶段 · 20 天','10.19—11.07'],['open-swatch','自主安排 · 41 天','11.08—12.18']]){const span=node('span');span.append(node('i','swatch '+cls),node('span','',label),node('small','',dates));legend.append(span)}const reg=node('div','registrations');reg.innerHTML='<span><i class="outline pre"></i>预报名 10.09—10.12</span><span><i class="outline formal"></i>正式报名 10.15—10.24</span><span>● 今天 · 报名每日 9:00—22:00</span>';board.append(legend,reg);const grid=node('ol','days');grid.id='days';grid.setAttribute('aria-label','10月9日至12月18日的71个连续日期');for(const d of days){const ts=tasksFor(d,doc),done=doneCount(ts),a=link('',dayURL(d.date),'day '+d.phase+(d.event?' '+d.event.kind:'')+(d.stamp===today?' today-day':'')+(d.stamp<today?' past':'')+(done===ts.length?' complete':''));a.setAttribute('aria-label',`${d.short}，${phaseName[d.phase]}，${d.year?d.year+'年真题，':''}完成 ${done}/${ts.length} 项${d.event?'，'+d.event.label+' '+d.event.time:''}`);if(d.stamp===today)a.setAttribute('aria-current','date');const time=node('time','',d.short);time.dateTime=d.date;a.append(time,node('span','tile-label',d.phase==='foundation'?`基础第 ${d.phaseDay} 天`:d.phase==='practice'?`${d.year} 年真题`:'每日 200 词'),node('span','tile-count',`${done} / ${ts.length} 项`));if(d.event)a.append(node('span','event',d.event.short));else{const track=node('span','mini-track'),fill=node('i');fill.style.width=done/ts.length*100+'%';track.append(fill);a.append(track)}const li=node('li');li.append(a);grid.append(li)}board.append(grid);const foot=node('div','board-foot');foot.append(node('span','','真题每天：政治、英语、数学、自动控制理论各 1 套'),node('span','','每日 200 词 · 任意一天都可新增任务'));board.append(foot);root.append(board);const finish=node('section','finish'),text=node('div');text.append(node('strong','','初试开始'),node('p','','把每一项完成，带着准备走进考场。'));finish.append(text,node('time','','2026.12.19 — 12.20'));root.append(finish,logTools());
}
function renderDay(root,d){
 activeDay=d;document.title=`${d.short} · ${phaseName[d.phase]}｜一天一格`;
 const nav=node('nav','day-nav'),adj=node('div','actions');nav.append(link('← 返回全局',homeURL()));if(d.i>0)adj.append(link('← 前一天',dayURL(days[d.i-1].date)));if(d.i<70)adj.append(link('后一天 →',dayURL(days[d.i+1].date)));nav.append(adj);const ts=tasksFor(d,doc),done=doneCount(ts),week=weekdays[new Date(d.stamp).getUTCDay()],hero=headline(`${d.short} · 星期${week}`,d.phase==='foundation'?`基础第 ${d.phaseDay} / 10 天。${d.i<9?'高数与线代并行，880 落实到题。':d.i<10?'今天数学只安排线代，自控完成第 10 天课程。':'今天安排线代二次型与单词，按计划收好基础。'}`:d.phase==='practice'?`${d.year} 年真题：政治、英语、数学、自控，每科 1 套。`:'200 个单词持续推进，也可以添加今天的复习任务。',`${phaseName[d.phase]} / 第 ${d.i+1} 个备考日`,true),count=node('div','count');count.append(node('strong','',done),node('span','',`/ ${ts.length} 项`),node('small','','今天已完成'));hero.append(count);root.append(nav,hero,syncbar());
 const layout=node('div','day-layout'),taskPanel=node('section','task-panel'),panelHeading=node('div','panel-heading');panelHeading.append(node('h2','','今天的任务'),button('＋ 新建任务','primary',()=>openTask(d.date)));taskPanel.append(panelHeading);
 for(const subject of subjects){const groupTasks=ts.filter(t=>t.subject===subject);if(!groupTasks.length)continue;const group=node('section','group'),title=node('h3','group-title');title.append(node('span','',subject),node('span','',`${doneCount(groupTasks)} / ${groupTasks.length}`));group.append(title);for(const t of groupTasks){const row=node('div','task-row'+(doc.checked.includes(t.id)?' done':'')),label=node('label'),input=document.createElement('input');input.type='checkbox';input.checked=doc.checked.includes(t.id);input.dataset.taskId=t.id;input.setAttribute('aria-label',t.title);input.addEventListener('change',()=>store.edit(t.id,input.checked));const copy=node('span','task-copy');copy.append(node('strong','',t.title));if(t.notes)copy.append(node('small','',t.notes));if(!t.builtin)copy.append(node('span','custom-tag','自建任务'));label.append(input,copy);row.append(label);if(!t.builtin){const del=node('button','delete-task','×');del.type='button';del.setAttribute('aria-label','删除任务：'+t.title);del.addEventListener('click',()=>{removeID=t.id;$('delete-description').textContent=t.title;$('delete-dialog').showModal()});row.append(del)}group.append(row)}taskPanel.append(group)}
 layout.append(taskPanel);const aside=node('aside'),progress=node('section','side-panel');progress.append(node('h2','','今日完成度'));const daily=node('div','daily-progress'),ptext=node('div');ptext.append(node('div','big-stat',`${done} / ${ts.length}`),node('p','','已完成 / 今日全部任务'));daily.append(ring(done,ts.length,'var(--lime)','今日完成度'),ptext);progress.append(daily);const subjectLines=node('div','subject-lines');for(const subject of subjects){const items=ts.filter(t=>t.subject===subject);if(!items.length)continue;const line=node('div','subject-line'),labels=node('div');labels.append(node('span','',subject),node('span','',`${doneCount(items)} / ${items.length}`));const bar=document.createElement('progress');bar.max=items.length;bar.value=doneCount(items);bar.setAttribute('aria-label',subject+'完成进度');line.append(labels,bar);subjectLines.append(line)}progress.append(subjectLines);aside.append(progress);
 if(d.course){const panel=node('section','side-panel');panel.append(node('h2','','国科大 857 · 自控课程'),node('h3','lesson-heading',d.course[0]),node('p','course-total',`${d.course[1].length} 节 · 合计 ${duration(courseSeconds(d.course[1]))}`),node('p','','边看课边写讲义，讲义单独勾选完成。'));const list=node('ol','lesson-list');for(const [number,title,time]of d.course[1]){const li=node('li');li.append(node('span','',number),node('span','',title),node('time','',time));list.append(li)}panel.append(list);aside.append(panel)}
 const rhythm=node('section','side-panel');rhythm.append(node('h2','','阶段安排'));if(d.phase==='foundation'){if(d.calculus)rhythm.append(node('p','',`高数 880：${d.calculus.title}，第 ${d.calculus.day}/${d.calculus.total} 天`));rhythm.append(node('p','',`线代 880：${d.algebra.title}，第 ${d.algebra.day}/${d.algebra.total} 天`),node('p','','10.09—10.18 基础阶段；10.19 开始 2007 年真题。'))}else if(d.phase==='practice')rhythm.append(node('p','',`今天 ${d.year} 年，${d.i<29?'下一天 '+(d.year+1)+' 年。':'完成后结束 20 年真题阶段。'}`),node('p','','四科各一套，200 个单词照常完成。'));else rhythm.append(node('p','','自主安排阶段，每天保留单词任务。用“新建任务”补充复习、错题和模拟。'));if(d.event)rhythm.append(node('p','event-note',`${d.event.label} · ${d.event.time}（北京时间）`));aside.append(rhythm);layout.append(aside);root.append(layout,logTools());
}
function render(){const focus=document.activeElement?.dataset?.taskId;today=todayStamp();$('today-date').textContent=new Date(today).toISOString().slice(0,10).replaceAll('-','.')+' · 星期'+weekdays[new Date(today).getUTCDay()];$('today-date').dateTime=new Date(today).toISOString().slice(0,10);activeDay=null;const root=$('app');root.replaceChildren();const query=new URLSearchParams(location.search),date=query.get('day');if(date&&!byDate.has(date)){const section=node('section','not-found');section.append(node('h1','','这一天不在当前备考计划中'),link('返回 71 天全局',homeURL(),'btn'));root.append(section)}else if(date)renderDay(root,byDate.get(date));else{document.title='一天一格 · 考研作战表';renderHome(root)}renderStatus();if(focus){const input=[...document.querySelectorAll('input[data-task-id]')].find(n=>n.dataset.taskId===focus);input?.focus({preventScroll:true})}}
const store=new PlannerStore({storage,onChange:next=>{doc=next;render()},onStatus:state=>{syncState=state;renderStatus()}});doc=store.doc;render();store.status();store.schedule(300);
function openTask(date){$('task-form').reset();$('task-date').value=date;$('task-error').textContent='';$('task-dialog').showModal();$('task-title').focus()}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
$('task-form').addEventListener('submit',event=>{event.preventDefault();const title=$('task-title').value.trim(),date=$('task-date').value;if(!title||!byDate.has(date)){$('task-error').textContent='请填写任务名称，并选择计划范围内的日期。';return}try{store.addTask({id:'custom:'+crypto.randomUUID(),date,title,subject:$('task-subject').value,notes:$('task-notes').value.trim(),createdAt:new Date().toISOString()});$('task-dialog').close();message('任务已添加，已加入当天进度。')}catch(error){$('task-error').textContent=error.message}});
$('confirm-delete').addEventListener('click',()=>{if(removeID)store.deleteTask(removeID);removeID=null;$('delete-dialog').close();message('任务已移除。')});
$('sync-form').addEventListener('submit',async event=>{event.preventDefault();$('connect-sync').disabled=true;$('setup-status').textContent='正在连接并同步…';try{await store.connect($('github-token').value,$('remember-token').checked);$('github-token').value='';$('sync-dialog').close();message('自动保存已连接。')}catch(error){$('setup-status').textContent=error.message}finally{$('connect-sync').disabled=false}});
$('sync-dialog').addEventListener('close',()=>{$('github-token').value=''});
$('copy-sync').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(store.token);$('setup-status').textContent='连接已复制。仅粘贴到你自己的作战表设置中。'}catch{$('setup-status').textContent='当前浏览器不允许复制，请重试。'}});
$('disconnect-sync').addEventListener('click',()=>{store.disconnect();$('setup-status').textContent='连接已清除，任务与日志继续保留。'});
if(new URLSearchParams(location.search).get('setup')==='github')$('sync-dialog').showModal();
window.addEventListener('online',()=>store.sync(true));
function resume(){try{const remembered=storage.getItem('exam-days-auto-token-v1');if(remembered&&!store.token)store.token=remembered}catch{}if(today!==todayStamp())render();store.schedule(300);store.status()}
window.addEventListener('focus',resume);document.addEventListener('visibilitychange',()=>{if(!document.hidden)resume()});
window.addEventListener('storage',event=>{if(event.key==='exam-days-auto-token-v1'){store.token=event.newValue||'';store.status();store.schedule(300)}if(event.key==='kaoyan-planner-v3'&&!store.running&&!Object.keys(store.pending.checks).length&&!Object.keys(store.pending.tasks).length){try{store.doc=validateDocument(JSON.parse(event.newValue));doc=store.doc;render();store.schedule(300)}catch{}}});
setInterval(()=>{if(today!==todayStamp())render()},60000);
